# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cx0VVZu5Ad7aVN4ASBVNH33mZZlAQy9k
"""

# app.py - Streamlit frontend for Food Vision Ultra
import streamlit as st
from src.model_loader import get_model, load_model_from_path
from src.preprocessing import preprocess_image
from src.predictor import predict_topk
from PIL import Image
import io, os, json

st.set_page_config(page_title="Food Vision Ultra", layout="wide")
st.title("Food Vision Ultra — Food-101 demo")
st.write("Upload an image and (optionally) a model checkpoint. The app will show top-5 predictions.")

# Config
DEFAULT_MODEL_PATH = "models/food101_best.pth"
LABELS_PATH = "src/label_map.json"

# Load labels
if os.path.exists(LABELS_PATH):
    with open(LABELS_PATH, "r") as f:
        labels = json.load(f)
else:
    labels = {str(i): f"class_{i}" for i in range(101)}

st.sidebar.header("Model")
uploaded_ckpt = st.sidebar.file_uploader("Upload a .pth checkpoint (optional)", type=["pth","pt","bin"])
use_local = st.sidebar.checkbox("Load model from repo (models/food101_best.pth)", value=True)

# Build model skeleton
model = get_model(num_classes=len(labels))

# Load checkpoint (uploaded takes precedence)
loaded = False
if uploaded_ckpt is not None:
    try:
        # uploaded_ckpt is a SpooledTemporaryFile-like object from Streamlit
        model = load_model_from_path(model, uploaded_ckpt, from_bytes=True)
        st.sidebar.success("Loaded uploaded checkpoint.")
        loaded = True
    except Exception as e:
        st.sidebar.error(f"Failed to load uploaded checkpoint: {e}")
elif use_local and os.path.exists(DEFAULT_MODEL_PATH):
    try:
        model = load_model_from_path(model, DEFAULT_MODEL_PATH, from_bytes=False)
        st.sidebar.success("Loaded checkpoint from models/food101_best.pth")
        loaded = True
    except Exception as e:
        st.sidebar.error(f"Failed to load checkpoint from {DEFAULT_MODEL_PATH}: {e}")

uploaded_img = st.file_uploader("Upload a food image", type=["jpg","jpeg","png"])
col1, col2 = st.columns([1,1])

if uploaded_img is not None:
    img = Image.open(io.BytesIO(uploaded_img.read())).convert("RGB")
    col1.image(img, caption="Uploaded image", use_column_width=True)

    if not loaded:
        col2.warning("No model loaded. Upload a checkpoint or add models/food101_best.pth to the repo.")
    else:
        inp = preprocess_image(img)  # returns tensor shape (1,3,H,W)
        topk = predict_topk(model, inp, k=5)
        col2.subheader("Top-5 Predictions")
        for idx, prob in topk:
            name = labels.get(str(idx), str(idx))
            col2.write(f"{name}: {prob:.4f}")
else:
    st.info("Upload an image to get predictions. For the first run, upload your model in the sidebar or place it under models/food101_best.pth.")