# -*- coding: utf-8 -*-
"""model_loader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jfwtIUZPDbVYvnffgE3fFaisXAy_w3mK
"""

# src/model_loader.py
import torch
import torch.nn as nn
from torchvision import models
import io

IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD  = [0.229, 0.224, 0.225]

def get_model(num_classes=101, device=None):
    """
    Create a ResNet50 model with final fc replaced.
    Model is returned on the chosen device.
    """
    device = device or (torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu"))
    model = models.resnet50(pretrained=False)
    in_features = model.fc.in_features
    model.fc = nn.Linear(in_features, num_classes)
    model.to(device)
    model.eval()
    return model

def load_model_from_path(model, ckpt, from_bytes=False, device=None):
    """
    Load checkpoint into `model`.
    - If from_bytes=True, `ckpt` is an uploaded file-like object or bytes.
    - If from_bytes=False, `ckpt` is a filesystem path string.
    """
    device = device or (torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu"))
    model.to(device)

    if from_bytes:
        # Streamlit uploaded file is a SpooledTemporaryFile; torch.load accepts it.
        if isinstance(ckpt, (bytes, bytearray)):
            state = torch.load(io.BytesIO(ckpt), map_location=device)
        else:
            # e.g. SpooledTemporaryFile
            state = torch.load(ckpt, map_location=device)
    else:
        state = torch.load(ckpt, map_location=device)

    # Support both state_dict and full checkpoint dict
    if isinstance(state, dict) and "model_state_dict" in state:
        state_dict = state["model_state_dict"]
    else:
        state_dict = state

    model.load_state_dict(state_dict)
    model.to(device)
    model.eval()
    return model