# -*- coding: utf-8 -*-
"""preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y2hJvTCOy4vFpRj6yTF1jB8Xgwdnph_8
"""

# src/preprocessing.py
from torchvision import transforms
from PIL import Image
import torch

IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD  = [0.229, 0.224, 0.225]

preprocess = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD)
])

def preprocess_image(pil_img):
    """
    Input: PIL image
    Output: torch.Tensor shape (1,3,H,W) dtype float
    """
    if not isinstance(pil_img, Image.Image):
        pil_img = Image.fromarray(pil_img)
    return preprocess(pil_img).unsqueeze(0)